FROM wearlab:sdk

# Dependencias graficas y de audio que necesita la ventana del emulador (Qt + X11 + Pulse)
RUN apt-get update && apt-get install -y --no-install-recommends \
      libx11-6 libxext6 libxrender1 libxrandr2 libxfixes3 libxdamage1 libxcomposite1 \
      libxkbcommon0 libxkbcommon-x11-0 libxcb1 libxcb-glx0 libxcb-keysyms1 libxcb-image0 \
      libxcb-shm0 libxcb-icccm4 libxcb-sync1 libxcb-xfixes0 libxcb-shape0 libxcb-randr0 \
      libxcb-render-util0 libxcb-xinerama0 libxcb-xkb1 libxcb-util1 libxcb-cursor0 \
      libfontconfig1 libfreetype6 libdbus-1-3 libglib2.0-0 libgtk-3-0 \
      libpulse0 pulseaudio-utils libsm6 libice6 \
      libopengl0 libegl1 libgbm1 mesa-utils \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y --no-install-recommends \
      libxkbfile1 libxmu6 libxaw7 libxpm4 x11-utils \
    && rm -rf /var/lib/apt/lists/*
